### ISSUE TITLE
参考建议

### ISSUE THREAD

**Issue by TSc2end** [detiam/Linux-TTY-UTF-8-Patch#2]
国内的麒麟操作系统（V10版本）已经实现了终端正常输出中文字符了，可以参考下；
我测试了桌面版和服务器版，都是正常的。服务器版本有两种内核，一种基于centos内核，另一种基于openEuler内核，我测试基于centos内核是正常的，openEuler内核没有测试过。社区版本优麒麟系统不支持终端显示中文（这个就是Ubuntu换皮）。

**Comment by TSc2end** [comment]
我测试了openEuler 20.03 LTS SP1，并不支持中文输出

**Comment by detiam** [comment]
那当然优先使用有支持的内核咯。

**Comment by TSc2end** [comment]
断断续续研究了一个月，终于大概搞明白CJKTTY的实现原理了，  简单来说就是用两个字符拼接为一个中文字符。根据各位大佬的资料，我去查阅了麒麟内核的编译配置文件，基本可以确认麒麟的内核也都是打了CJKTTY补丁实现了中文显示。ARCH也有大佬放出了带CJK补丁的内核。目前来看CJKTTY是唯一的实现内核中文的方法了，按照CJKTTY作者的说法，wayland可能带来根本性的改变吧，期待wayland的发展了~

PS：麒麟这个商业版还不开源，大家还是去试试ARCH大佬的打包内核，或者自己给内核打补丁吧。。。。
